# CI

name: Makefile CI
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check # Not recommended "|| true"

    - name: Run distcheck
      run: make distcheck # Not recommended "|| true"
